---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Deploy nginx config (full)
  template:
    src: caliph_full.conf.j2
    dest: /etc/nginx/sites-available/caliph.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/caliph.conf
    dest: /etc/nginx/sites-enabled/caliph.conf
    state: link
  notify: Restart nginx

- name: Deploy other config template 
  template:
    src: other_full.conf.j2
    dest: /etc/nginx/sites-available/other.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Enable other site
  file:
    src: /etc/nginx/sites-available/other.conf
    dest: /etc/nginx/sites-enabled/other.conf
    state: link
  notify: Restart nginx

- name: Ensure nginx running
  service:
    name: nginx
    state: started
    enabled: yes
